### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [RIYIC/system_cron#1]
Hi
This command is true?

include_recipe "system_cron::default"
cron_d "clean_memory" do
        minute  */20
        hour    *
        day     *
        month   *
        weekday *
        command "sh /etc/memory-clean.sh"
        user    "root"
    end

Thanks

**Comment by alambike** [comment]
Hi,
This cookbook is a wrapper over [opscode cron cookbook](https://github.com/opscode-cookbooks/cron), and **cron_d** is a LWRP defined there so you could configure a cron task in `/etc/cron.d` with 

``` ruby
include_recipe "cron::default"

cron_d "clean_memory" do
    minute     "*/20"
    command    "sh /etc/memory-clean.sh"
    user       "root"
end
```
